[package]
name = "scarab_macros"
description = "Provides useful procedural macros for the scarab_engine library"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
syn = "2.0"
synstructure = "0.13"
quote = "1.0"

[lib]
crate-type = ["proc-macro"]
edition = "2021"
